version: '3'

services:

  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
      - "3333:3333"
      - "4200:4200"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

volumes:
  mongodb-data:
  node_modules:

